In [209]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.colors as mcolors
import matplotlib.gridspec as gridspec

import seaborn as sns

from pyfish import process_data, setup_figure, fish_plot
from matplotlib.sankey import Sankey

sns.set_style('ticks',
              rc={'axes.facecolor': (0, 0, 0, 0)})
sns.set_context('talk')

from matplotlib import rcParams, colors, cm
rcParams['font.family'] = 'sans-serif'
rcParams['figure.dpi'] = 150

pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 100)

In [210]:
df = pd.read_excel("../../data/data.xlsx")

In [211]:
df["GPSC"] = df["GPSC"].astype("string")
df["serotype_cons"] = df["serotype_cons"].astype("string")
df["serotype_geno"] = df["serotype_geno"].astype("string")
df["serotype_pheno"] = df["serotype_pheno"].astype("string")
df["ST"] = df["ST"].astype("string")

In [212]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['year'] = df['date'].dt.year

In [213]:
df["year"].value_counts()

year
2018    95
2017    88
2024    82
2023    78
2019    77
2015    72
2005    72
2022    70
2016    63
2007    59
2004    59
2003    59
2014    52
2009    52
2006    52
2013    50
2008    47
2002    46
2021    44
2020    41
2010    36
2011    27
2012    25
Name: count, dtype: int64

In [214]:
# vaccines introduction
pcv7 = 2006
pcv13 = 2011
covid19 = 2020
pcv15 = 2023

In [215]:
# Define vaccine periods
def assign_vaccine_period(year):
    if year < 2005:
        return "pre-PCV7"
    elif 2005 <= year < 2011:
        return "PCV7"
    elif 2011 <= year < 2015:
        return "early-PCV13"
    elif 2015 <= year < 2020:
        return "late-PCV13"
    elif 2020 <= year < 2023:
        return "COVID19"
    else:  # 2020+ COVID impact
        return "PCV15"

df['vaccine_period'] = df['year'].apply(assign_vaccine_period)

prevalence = df.groupby(['vaccine_period', 'serotype_pheno']).size().reset_index(name='count')

# Get top 10 per period
top10_per_period = prevalence.groupby('vaccine_period', group_keys=False).apply(lambda x: x.nlargest(10, 'count'))

print(top10_per_period)

    vaccine_period serotype_pheno  count
21         COVID19              3     35
32         COVID19              8     19
16         COVID19            22F     15
14         COVID19            19F     12
33         COVID19             9N      9
13         COVID19            19A      7
18         COVID19            23B      7
0          COVID19            10A      5
2          COVID19            11A      3
4          COVID19             14      3
55           PCV15              3     25
66           PCV15              8     24
50           PCV15            22F     14
52           PCV15            23B      8
62           PCV15             38      8
67           PCV15             9N      8
36           PCV15            10A      7
43           PCV15            15B      6
51           PCV15            23A      6
42           PCV15            15A      5
93            PCV7              3     30
76            PCV7             14     27
99            PCV7              4     25
103           PCV7             7F     25
82            PCV7            19A     24
83            PCV7            19F     19
90            PCV7            23F     19
107           PCV7             9V     18
81            PCV7            18C     15
100           PCV7             6A     14
131    early-PCV13              3     25
121    early-PCV13            19A     11
143    early-PCV13             7F     11
122    early-PCV13            19F      8
129    early-PCV13            24F      8
144    early-PCV13              8      7
137    early-PCV13            35F      6
139    early-PCV13              4      6
145    early-PCV13             9N      6
124    early-PCV13            22F      5
169     late-PCV13              3     55
183     late-PCV13              8     45
151     late-PCV13            12F     35
164     late-PCV13            22F     26
184     late-PCV13             9N     22
159     late-PCV13            19A     18
152     late-PCV13             14     15
166     late-PCV13            23B     14
153     late-PCV13            15A     13
150     late-PCV13            11A     12
191       pre-PCV7             14     20
212       pre-PCV7             7F     16
203       pre-PCV7              3     13
200       pre-PCV7            23F     12
194       pre-PCV7            18C     11
196       pre-PCV7            19F     10
208       pre-PCV7              4     10
187       pre-PCV7              1      9
211       pre-PCV7             6B      8
213       pre-PCV7              8      8

/scratch/local/332170/ipykernel_3848849/894463791.py:21: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  top10_per_period = prevalence.groupby('vaccine_period', group_keys=False).apply(lambda x: x.nlargest(10, 'count'))

In [216]:
# Define serotype groups by PCV category
pcv7 = ["4", "6B", "9V", "14", "18C", "19F", "23F"]
pcv13 = ["1", "3", "5", "6A", "7F", "19A"]
pcv15 = ["22F", "33F"]
pcv20 = ["8", "10A", "11A", "12F", "15B"]
ppv23 = ["2", "9N", "17F", "20"]
v116 = ["15A", "15C", "16F", "23A", "23B", "24F", "31", "35B"]

In [217]:
# Define serotype groups by PCV category
pcv7 = ["4", "6B", "9V", "14", "18C", "19F", "23F"]
pcv13 = ["1", "3", "5", "6A", "7F", "19A"]
pcv15 = ["22F", "33F"]
pcv20 = ["8", "10A", "11A", "12F", "15B"]
ppv23 = ["2", "9N", "17F", "20"]
v116 = ["15A", "15C", "16F", "23A", "23B", "24F", "31", "35B"]

VT = pcv7 + pcv13 + pcv15

df["isVT"] = df["serotype_cons"].isin(VT).astype(int)
df["isPCV7"] = df["serotype_cons"].isin(pcv7).astype(int)
df["isPCV13"] = df["serotype_cons"].isin(pcv13).astype(int)
df["isPCV15"] = df["serotype_cons"].isin(pcv15).astype(int)

In [218]:
df["age"] = df["age"].round().astype("Int64")

In [219]:
# Define age groups

def assign_age_groups(age):
    if pd.isna(age):
        return pd.NA
    elif age < 5:
        return "<5 years"
    elif age < 17:
        return "5-17 years"
    elif age < 45:
        return "18-44 years"
    elif age < 65:
        return "45-64 years"
    else:
        return ">=65 years"

df['age_group'] = df['age'].apply(assign_age_groups)

prevalence = df.groupby(['age_group', 'serotype_pheno']).size().reset_index(name='count')

In [220]:
prevalence

       age_group serotype_pheno  count
0    18-44 years              0      3
1    18-44 years              1      4
2    18-44 years             10      1
3    18-44 years            10A      3
4    18-44 years            10B      1
..           ...            ...    ...
201   >=65 years             7F     27
202   >=65 years              8     49
203   >=65 years              9      3
204   >=65 years             9N     30
205   >=65 years             9V     16

[206 rows x 3 columns]

In [221]:
df['isNVT'] = 1 - df['isVT']

In [222]:
vaccine_cols = ['pre-PCV7', 'PCV7', 'early-PCV13', 'late-PCV13', 'PCV15', 'COVID19']
for col in vaccine_cols:
    df[col] = (df['vaccine_period'] == col).astype(int)

In [223]:
counts = df["serotype_cons"].value_counts()

df["dominant_serotype"] = (
    df["serotype_cons"]
    .map(counts)
    .gt(24)
    .where(df["serotype_cons"].notna())
    .astype("Int64")
)

In [224]:
counts = df["GPSC"].value_counts()

df["dominant_GPSC"] = (
    df["GPSC"]
    .map(counts)
    .gt(24)
    .where(df["GPSC"].notna())
    .astype("Int64")
)

In [225]:
counts

GPSC
3               142
12               99
83               78
7                67
19               65
15               65
16               64
6                59
4                58
32               46
27               46
18               44
39               40
36               32
76               25
11               25
50               24
31               22
49               20
44               19
5                18
35               17
24               17
38               17
Not_assigned     14
57                9
29                9
10                8
1                 7
99                6
146               6
43                6
175               5
162               5
157               5
23                5
119               5
124               5
904;9             5
68                4
75                4
61                4
98                4
9                 4
46                4
67                4
48                3
13                3
115               3
2                 2
45                2
191               2
271               2
229               2
60                2
139               2
234               2
580               2
59                2
386               2
72                2
47                2
576               2
391               1
198               1
14                1
95                1
64                1
376               1
1134              1
378               1
8                 1
841               1
147               1
230               1
336               1
123               1
30                1
1135              1
739               1
224               1
727               1
316               1
156               1
26                1
321               1
1125              1
1268              1
170               1
126               1
55                1
155               1
215               1
89                1
310               1
465               1
109               1
291               1
-                 1
420               1
Name: count, dtype: Int64

In [226]:
df_m = df[df.assembly == "missing"]

In [231]:
df_m

,lab-nr,working-nr,sample-nr,patient-nr,material,others,sepsis,HIV+,meningitis,covid,date,age,sex,serotype_pheno,serotype_geno,serogroup_match,serotype_match,serotype_cons,serotype_cons_reason,ST,GPSC,bad_quality,penicillin_men_geno,penicillin_nonmen_geno,penicillin_MIC_geno,pbp1a,pbp2b,pbp2x,ceftriaxone_men_geno,ceftriaxone_nonmen_geno,ceftriaxone_MIC_geno,amoxicillin_geno,amoxicillin_MIC_geno,CSP,ply_allele_aa,fasta,reads,sequencing_technology,reads_location,assembly,assembly_location,assembly_contigs,assembly_length,assembly_N50,assembly_closed,year,vaccine_period,isVT,isPCV7,isPCV13,isPCV15,age_group,isNVT,pre-PCV7,PCV7,early-PCV13,late-PCV13,PCV15,COVID19,dominant_serotype,dominant_GPSC
96,3152034,97,1197.25,421217.0,material_blood,1.0,0.0,0.0,0.0,0.0,2020-01-17,62,F,3,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97,NaN,NaN,NaN,missing,NaN,NaN,NaN,NaN,not_assembled,2020,COVID19,0,0,0,0,45-64 years,1,0,0,0,0,0,1,<NA>,<NA>
123,3103882,124,1193.45,1421587.0,material_blood,1.0,0.0,0.0,0.0,0.0,2019-10-06,2,M,3,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,124,NaN,NaN,NaN,missing,NaN,NaN,NaN,NaN,not_assembled,2019,late-PCV13,0,0,0,0,<5 years,1,0,0,0,1,0,0,<NA>,<NA>
239,2831940,240,1176.51,701065.0,material_CSF,1.0,0.0,0.0,1.0,0.0,2018-03-03,8,M,35B,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,missing,NaN,NaN,NaN,NaN,not_assembled,2018,late-PCV13,0,0,0,0,5-17 years,1,0,0,0,1,0,0,<NA>,<NA>
261,2811262,262,1174.35,405337.0,material_other,1.0,0.0,0.0,0.0,0.0,2018-01-18,49,M,8,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_262.fq.gz,PacBio,/storage/workspaces/ifik_miclab/ifik_miclab1/P...,missing,NaN,NaN,NaN,NaN,not_assembled,2018,late-PCV13,0,0,0,0,45-64 years,1,0,0,0,1,0,0,<NA>,<NA>
262,2809608,263,1174.14,457078.0,material_blood,1.0,0.0,0.0,0.0,0.0,2018-01-15,54,M,8,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_263.fq.gz,PacBio,/storage/workspaces/ifik_miclab/ifik_miclab1/P...,missing,NaN,NaN,NaN,NaN,not_assembled,2018,late-PCV13,0,0,0,0,45-64 years,1,0,0,0,1,0,0,<NA>,<NA>
265,2809016,266,1173.81,1281646.0,material_blood,1.0,1.0,0.0,0.0,0.0,2018-01-13,55,F,8,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_266.fq.gz,PacBio,/storage/workspaces/ifik_miclab/ifik_miclab1/P...,missing,NaN,NaN,NaN,NaN,not_assembled,2018,late-PCV13,0,0,0,0,45-64 years,1,0,0,0,1,0,0,<NA>,<NA>
267,2805700,268,1173.24,959397.0,material_blood,1.0,1.0,0.0,0.0,0.0,2018-01-06,3,M,8,<NA>,No_Match,No_Match,8,No genome annotation found,<NA>,<NA>,length,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_268,A_268.fq.gz,PacBio,/storage/workspaces/ifik_miclab/ifik_miclab1/P...,missing,NaN,NaN,NaN,NaN,not_assembled,2018,late-PCV13,0,0,0,0,<5 years,1,0,0,0,1,0,0,1,<NA>
288,2789539,289,1170.76,1271133.0,material_other,1.0,0.0,0.0,0.0,0.0,2017-11-25,81,F,8,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_289.fq.gz,PacBio,/storage/workspaces/ifik_miclab/ifik_miclab1/P...,missing,NaN,NaN,NaN,NaN,not_assembled,2017,late-PCV13,0,0,0,0,>=65 years,1,0,0,0,1,0,0,<NA>,<NA>
294,2771619,295,1169.70,1081734.0,material_blood,1.0,0.0,0.0,0.0,0.0,2017-10-13,39,F,8,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_295.fq.gz,PacBio,/storage/workspaces/ifik_miclab/ifik_miclab1/P...,missing,NaN,NaN,NaN,NaN,not_assembled,2017,late-PCV13,0,0,0,0,18-44 years,1,0,0,0,1,0,0,<NA>,<NA>
306,2724683,307,1168.18,356414.0,material_blood,1.0,1.0,0.0,0.0,0.0,2017-06-16,66,M,8,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_307.fq.gz,PacBio,/storage/workspaces/ifik_miclab/ifik_miclab1/P...,missing,NaN,NaN,NaN,NaN,not_assembled,2017,late-PCV13,0,0,0,0,>=65 years,1,0,0,0,1,0,0,<NA>,<NA>
318,2700452,319,1166.32,487701.0,material_blood,1.0,1.0,0.0,0.0,0.0,2017-04-20,76,M,8,<NA>,No_Match,No_Match,8,No genome annotation found,<NA>,<NA>,length,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_319,A_319.fq.gz,PacBio,/storage/workspaces/ifik_miclab/ifik_miclab1/P...,missing,NaN,NaN,NaN,NaN,not_assembled,2017,late-PCV13,0,0,0,0,>=65 years,1,0,0,0,1,0,0,1,<NA>
335,2677621,336,1163.65,1208761.0,material_blood,1.0,0.0,0.0,0.0,0.0,2017-02-23,61,F,8,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_336.fq.gz,PacBio,/storage/workspaces/ifik_miclab/ifik_miclab1/P...,missing,NaN,NaN,NaN,NaN,not_assembled,2017,late-PCV13,0,0,0,0,45-64 years,1,0,0,0,1,0,0,<NA>,<NA>
363,2654688,364,1159.81,1151236.0,material_blood,1.0,0.0,0.0,0.0,0.0,2016-12-31,71,F,8,<NA>,No_Match,No_Match,8,No genome annotation found,<NA>,<NA>,length,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_364,A_364.fq.gz,PacBio,/storage/workspaces/ifik_miclab/ifik_miclab1/P...,missing,NaN,NaN,NaN,NaN,not_assembled,2016,late-PCV13,0,0,0,0,>=65 years,1,0,0,0,1,0,0,1,<NA>
384,2586624,385,1155.70,387006.0,material_blood,1.0,0.0,0.0,0.0,0.0,2016-07-10,51,M,8,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_385.fq.gz,PacBio,/storage/workspaces/ifik_miclab/ifik_miclab1/P...,missing,NaN,NaN,NaN,NaN,not_assembled,2016,late-PCV13,0,0,0,0,45-64 years,1,0,0,0,1,0,0,<NA>,<NA>
401,2556755,402,1154.07,732660.0,material_blood,1.0,1.0,0.0,0.0,0.0,2016-04-25,69,M,8,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_402.fq.gz,PacBio,/storage/workspaces/ifik_miclab/ifik_miclab1/P...,missing,NaN,NaN,NaN,NaN,not_assembled,2016,late-PCV13,0,0,0,0,>=65 years,1,0,0,0,1,0,0,<NA>,<NA>
436,2489495,437,1146.57,1084342.0,material_blood,1.0,1.0,0.0,0.0,0.0,2015-11-02,86,F,8,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_437.fq.gz,PacBio,/storage/workspaces/ifik_miclab/ifik_miclab1/P...,missing,NaN,NaN,NaN,NaN,not_assembled,2015,late-PCV13,0,0,0,0,>=65 years,1,0,0,0,1,0,0,<NA>,<NA>
504,2365193,505,1136.76,1025136.0,material_blood,1.0,0.0,0.0,0.0,0.0,2014-12-09,77,F,8,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_505.fq.gz,PacBio,/storage/workspaces/ifik_miclab/ifik_miclab1/P...,missing,NaN,NaN,NaN,NaN,not_assembled,2014,early-PCV13,0,0,0,0,>=65 years,1,0,0,1,0,0,0,<NA>,<NA>
552,2240604,553,1126.03,959185.0,material_blood,1.0,0.0,0.0,0.0,0.0,2013-12-04,2,F,8,<NA>,No_Match,No_Match,8,No genome annotation found,<NA>,<NA>,length,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_553,A_553.fq.gz,PacBio,/storage/workspaces/ifik_miclab/ifik_miclab1/P...,missing,NaN,NaN,NaN,NaN,not_assembled,2013,early-PCV13,0,0,0,0,<5 years,1,0,0,1,0,0,0,1,<NA>
557,2225436,558,1124.59,394507.0,material_blood,1.0,1.0,0.0,0.0,0.0,2013-10-16,67,M,8,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_558.fq.gz,PacBio,/storage/workspaces/ifik_miclab/ifik_miclab1/P...,missing,NaN,NaN,NaN,NaN,not_assembled,2013,early-PCV13,0,0,0,0,>=65 years,1,0,0,1,0,0,0,<NA>,<NA>
671,1826975,672,904.37,711082.0,material_blood,1.0,1.0,0.0,0.0,0.0,2010-03-06,82,F,8,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_672.fq.gz,PacBio,/storage/workspaces/ifik_miclab/ifik_miclab1/P...,missing,NaN,NaN,NaN,NaN,not_assembled,2010,PCV7,0,0,0,0,>=65 years,1,0,1,0,0,0,0,<NA>,<NA>
753,1649319,754,707.61,380885.0,material_blood,1.0,1.0,0.0,0.0,0.0,2008-10-06,50,F,8,<NA>,No_Match,No_Match,8,No genome annotation found,<NA>,<NA>,length,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_754,A_754.fq.gz,PacBio,/storage/workspaces/ifik_miclab/ifik_miclab1/P...,missing,NaN,NaN,NaN,NaN,not_assembled,2008,PCV7,0,0,0,0,45-64 years,1,0,1,0,0,0,0,1,<NA>
786,1558957,787,NaN,539076.0,material_other,1.0,0.0,0.0,0.0,0.0,2008-01-10,73,F,14,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,missing,NaN,NaN,NaN,NaN,not_assembled,2008,PCV7,0,0,0,0,>=65 years,1,0,1,0,0,0,0,<NA>,<NA>
802,1531008,803,605.57,30690.0,material_blood,1.0,1.0,0.0,0.0,0.0,2007-10-06,48,M,8,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_803.fq.gz,PacBio,/storage/workspaces/ifik_miclab/ifik_miclab1/P...,missing,NaN,NaN,NaN,NaN,not_assembled,2007,PCV7,0,0,0,0,45-64 years,1,0,1,0,0,0,0,<NA>,<NA>
866,1394776,867,504.16,424811.0,material_blood,1.0,0.0,0.0,0.0,0.0,2006-07-18,82,F,6A,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,missing,NaN,NaN,NaN,NaN,not_assembled,2006,PCV7,0,0,0,0,>=65 years,1,0,1,0,0,0,0,<NA>,<NA>
870,1383956,871,503.42,480084.0,material_blood,1.0,1.0,0.0,0.0,0.0,2006-06-10,67,M,4,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,missing,NaN,NaN,NaN,NaN,not_assembled,2006,PCV7,0,0,0,0,>=65 years,1,0,1,0,0,0,0,<NA>,<NA>
920,1292215,921,404.31,447680.0,material_blood,1.0,0.0,0.0,0.0,0.0,2005-08-09,51,F,8,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_921.fq.gz,PacBio,/storage/workspaces/ifik_miclab/ifik_miclab1/P...,missing,NaN,NaN,NaN,NaN,not_assembled,2005,PCV7,0,0,0,0,45-64 years,1,0,1,0,0,0,0,<NA>,<NA>
932,1261551,933,401.44,436751.0,material_blood,1.0,0.0,0.0,0.0,0.0,2005-04-26,49,F,8,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_933.fq.gz,PacBio,/storage/workspaces/ifik_miclab/ifik_miclab1/P...,missing,NaN,NaN,NaN,NaN,not_assembled,2005,PCV7,0,0,0,0,45-64 years,1,0,1,0,0,0,0,<NA>,<NA>
1061,1066791,1062,202.40,196140.0,material_blood,1.0,0.0,0.0,0.0,0.0,2003-06-04,43,M,6B,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,missing,NaN,NaN,NaN,NaN,not_assembled,2003,pre-PCV7,0,0,0,0,18-44 years,1,1,0,0,0,0,0,<NA>,<NA>
1130,943871,1131,101.02,313053.0,material_blood,1.0,0.0,0.0,0.0,0.0,2002-03-03,67,F,4,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,missing,NaN,NaN,NaN,NaN,not_assembled,2002,pre-PCV7,0,0,0,0,>=65 years,1,1,0,0,0,0,0,<NA>,<NA>
1237,3981679,1238,1229.68,1123690.0,material_blood,1.0,0.0,0.0,0.0,0.0,2023-08-12,41,M,23A,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,missing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,missing,NaN,NaN,NaN,NaN,NaN,2023,PCV15,0,0,0,0,18-44 years,1,0,0,0,0,1,0,<NA>,<NA>
1238,3985855,1239,1229.77,1560059.0,material_blood,1.0,0.0,0.0,0.0,0.0,2023-08-22,39,M,10A,<NA>,No_Match,No_Match,<NA>,Micrococcus luteus,<NA>,<NA>,Micrococcus luteus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1239,NaN,Illumina,/storage/workspaces/ifik_miclab/ifik_miclab1/P...,missing,NaN,243.0,4610338.0,57972.0,NaN,2023,PCV15,0,0,0,0,18-44 years,1,0,0,0,0,1,0,<NA>,<NA>
1270,4055039,1271,1236.05,1791718.0,material_blood,1.0,1.0,0.0,0.0,0.0,2024-01-22,77,M,22F,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,M. luteus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,missing,NaN,277.0,4701200.0,101649.0,NaN,2024,PCV15,0,0,0,0,>=65 years,1,0,0,0,0,1,0,<NA>,<NA>
1281,24K-071B0091,1282,1238.69,NaN,material_blood,NaN,NaN,NaN,NaN,NaN,2024-03-09,72,M,22F,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,M. luteus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,missing,NaN,494.0,4701356.0,77550.0,NaN,2024,PCV15,0,0,0,0,>=65 years,1,0,0,0,0,1,0,<NA>,<NA>
1287,24K-078B0119,1288,1239.21,NaN,material_other,NaN,NaN,NaN,NaN,NaN,2024-03-16,0,M,19F,<NA>,NaN,NaN,<NA>,NaN,<NA>,<NA>,length,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,missing,NaN,NaN,NaN,NaN,NaN,2024,PCV15,0,0,0,0,<5 years,1,0,0,0,0,1,0,<NA>,<NA>

In [227]:
df_m.to_excel("../../data/data_missing.xlsx", index=None)

In [228]:
df_f = df[df.assembly == "present"]

In [229]:
df_f = df_f.drop(columns=[
    "CSP",
    "ply_allele_aa",
    "fasta",
    "reads",
    "sequencing_technology",
    "reads_location",
    "assembly",
    "assembly_location",
    "assembly_contigs",
    "assembly_length",
    "assembly_N50",
    "assembly_closed"
])

In [230]:
df_f.to_excel("../../data/data_cleaned.xlsx", index=None)